# Generated by Django 5.1.2 on 2024-11-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_itemcarrinho_carrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='preco',
        ),
        migrations.AlterModelTable(
            name='carrinho',
            table='carrinho_carrinho',
        ),
        migrations.AlterModelTable(
            name='itemcarrinho',
            table='produtos_itemcarrinho',
        ),
    ]
