# Generated by Django 5.1.2 on 2024-11-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemcarrinho',
            table=None,
        ),
    ]
